const products=[
    {
        _id:'1',
        name:"boat airpode",
        image:'/images/boatimage.jpg',
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
        brand:'boat',
        category:"electronics",
        price:'10.99',
        countinstock:"10",
        rating:'4.5',
        numreviews:"12",
    },
    {
        _id:'2',
        name:"vivo mobile",
        image:'/images/vivoimage.jpg',
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
        brand:'vivo',
        category:"electronics",
        price:'10.99',
        countinstock:"10",
        rating:'2.5',
        numreviews:"4",
    },
    {
        _id:'3',
        name:"micromax mobile",
        image:'/images/micromaximge.jpg',
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
        brand:'micromax',
        category:"electronics",
        price:'10.99',
        countinstock:"10",
        rating:'4.5',
        numreviews:"8",
    },{
        _id:'1',
        name:"boat airpode",
        image:'/images/boatimage.jpg',
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        brand:'boat',
        category:"electronics",
        price:'10.99',
        countinstock:"10",
        rating:'3',
        numreviews:"5",
    },
    {
        _id:'2',
        name:"vivo mobile",
        image:'/images/vivoimage.jpg',
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
        brand:'vivo',
        category:"electronics",
        price:'10.99',
        countinstock:"9",
        rating:'5',
        numreviews:"12",
    },
    {
        _id:'3',
        name:"micromax mobile",
        image:'/images/micromaximge.jpg',
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
        brand:'micromax',
        category:"electronics",
        price:'10.99',
        countinstock:"10",
        rating:'3.5',
        numreviews:"15",
    }
]

export  default products;